In [20]:
#installing numpy
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [18]:
import numpy
numpy. __version__

'1.24.3'

In [14]:
#lists
l=list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
[str(c) for c in l]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [29]:
[type(item) for item in l]

[int, int, int, int, int, int, int, int, int, int]

In [21]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [24]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.random.normal(0,1,(3,3))

array([[ 0.27966837,  0.45969563,  0.62272118],
       [-0.53298466,  1.77427635, -1.86993373],
       [-0.00802782, -0.90001061, -0.3388178 ]])

In [33]:
#create and identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#set a random seed
np.random.seed(0)

In [35]:
x1=np.random.randint(10,size=6)#one dimension
x2=np.random.randint(10,size=(3,4))#two dimension
x3=np.random.randint(10,size=(3,4,5))#one dimension

In [36]:
print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [37]:
#In a multidimensional array,we need to specify row and column index
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
#1st row and 2nd column value
x2[2,3]

7

In [40]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#from first to 5th position
x[:5]

array([0, 1, 2, 3, 4])

In [42]:
#from 4th position to end
x[4:]

array([4, 5, 6, 7, 8, 9])

In [43]:
#return elements from first position step by two
x[1::2]

array([1, 3, 5, 7, 9])

In [44]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
#you can concatenate two or more arrays at once
x=np.array([1,2,3])
y=np.array([3,2,1])
z=[21,21,21]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [46]:
#load library-pd is just an alias .i used npd because its short and literally abbreviates pandas
import pandas as pd

In [51]:
#create a dataframe -dictionary is used here  where keys get converted to column names and values to row values
data=pd.DataFrame({'country':['russia','colomboia','chile','equador','nigeria'],
                              'rank':[121,40,100,130,11]})
data

country  rank
0     russia   121
1  colomboia    40
2      chile   100
3    equador   130
4    nigeria    11

In [52]:
data.describe()

rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [ ]:
#among other things,it shows